### ISSUE TITLE
User pop outs out of position

### ISSUE THREAD

**Issue by silent** [TakosThings/Metro-for-Discord#119]
**Describe the bug**
User pop-outs are out of position when clicking on users names in the chat. In the memberlist it seems okay for now.

**Screenshots**
![image](https://user-images.githubusercontent.com/36117192/66686545-6b621780-ec45-11e9-94ac-a463bcb97cbb.png)

**Comment by MrHugelberg** [comment]
I don't know if it rather open a new report for that.
the "go live" button is out of position as well. 
![Discord_2019-10-16_08-00-57](https://user-images.githubusercontent.com/25200709/66892189-4d046f00-efeb-11e9-8304-9fdfc9f6921c.png)
 I thought it fits perfect in here since its basically the same bug.

**Comment by tryoutuser** [comment]
Addition to @MrHugelberg report that is game icon and name appear to be transparent and clips over channel list in my display (1366x768), I suggest make a background for it like same with theme background. Also it seems latency indicator is bugged again.

**Comment by TakosThings** [comment]
> I don't know if I should rather open a new report for that.

Yes, unrelated bugs should go to new new issues, I've opened #120 for this one

**Comment by TakosThings** [comment]
Reopening this issue because they broke it again right after I did the update 🙃
