### ISSUE TITLE
Block icons in channel permission settings

### ISSUE THREAD

**Issue by tryoutuser** [TakosThings/Metro-for-Discord#153]
Already updated to v3.14.1
![image](https://user-images.githubusercontent.com/35561383/79494256-e5d47f80-804c-11ea-81f7-940f3022b183.png)

**Describe the bug**
Icons for checkmark and x-cross shown as block in channel permission settings

**Steps to reproduce**
Go to channel settings and permission tab

**Screenshots**
![image](https://user-images.githubusercontent.com/35561383/79494025-837b7f00-804c-11ea-979e-2e345e00eed0.png)

**Comment by tryoutuser** [comment]
ok i've just updated to v3.14.1a and it's same

**Comment by TakosThings** [comment]
This is likely caused by an out of date Segoe UI MDL2 Assets font on your PC. (For reference I have version 1.75, which I believe is the latest available).

I have heard of others fixing this by running a system file check, but I would recommend you do your own research. Always back up your important files before attempting fixes suggested by others.

**Comment by tryoutuser** [comment]
welp what i have is v1.68. does installing a new one from MSDN page about UWP design will work?

**Comment by TakosThings** [comment]
Unlikely, that one is v1.60i

**Comment by tryoutuser** [comment]
damn it
