### ISSUE TITLE
Spotify Controls Issue

### ISSUE THREAD

**Issue by nediaH** [TakosThings/Metro-for-Discord#192]
I just started using Metro for Discord. When I have Spotify Controls enabled and I'm listening to music the player underlaps the profile pic and the settings button causing it to look like the attached picture.  Thanks for any help.

![Desktop Screenshot 2020 11 17 - 14 18 37 69](https://user-images.githubusercontent.com/41041630/99437602-b3d81400-28e0-11eb-80c7-9e6bfad3243d.png)

**Comment by TakosThings** [comment]
I'm not currently maintaining any BD plugins, but anyone is welcome to [contribute](https://github.com/TakosThings/Metro-for-Discord/blob/master/.github/CONTRIBUTING.md#betterdiscord) to resolve this.

If you know your way around dev tools the fix is likely as simple as adding `margin-left: 48px` to the container.

**Comment by picoshmit** [comment]
same issue here, hope this will get a fix one day cuz its great theme!

**Comment by danperks** [comment]
Adding the custom CSS below fixes this roughly, might need to change value for your screen:
```
.container-6sXIoE {
    padding-left: 3vw;
}
```

**Comment by mantazzo** [comment]
Well, I'm not sure if something fixed itself or not, but SpotifyControls seem to work okay with the style for now. No additional CSS was required.

![paveikslas](https://user-images.githubusercontent.com/9445013/117891293-50db9e80-b2bf-11eb-94a1-7efeaf1d41d0.png)
