### ISSUE TITLE
Edge/UWP scroll animation

### ISSUE THREAD

**Issue by KibSquib48** [TakosThings/Metro-for-Discord#194]
This isn't really a necessity but I feel like it would be nice to have, and would improve the illusion of being a UWP app

Is it possible to add the scroll animation from Microsoft Edge? It's based on Chromium, which Electron is also based on, so I assume it would be possible right? And there are also some chrome extensions that enable smooth scrolling which is similar to UWP scrolling, so if the same implementation from Edge isn't possible is the extension method at least an option?

**Comment by TakosThings** [comment]
Ideally I'd like to be able to use a lot more animations, but I'm mostly hampered by Discord's shall we say... 'unique' way of doing things.

I don't believe there is a way of adding smooth scrolling with only CSS. There is the `scroll-behavior: smooth` property, but it doesn't really do much and has the added bonus of breaking lazy loading.

I'd say smooth scrolling in Edge is probably from some Microsoft special sauce, since even though there's a [flag](chrome://flags/#smooth-scrolling) in chrome, it doesn't appear to do anything.
