### ISSUE TITLE
Overlapping icons (with and without plugins) + some suggestions

### ISSUE THREAD

**Issue by abstraverse** [TakosThings/Metro-for-Discord#200]
On the ,,Home" screen, the one with chats, two tiles (Friends and Library as seen bellow) both have their icons, however Library icon is always under 1st server's icon on the server list. Pic:
![image](https://user-images.githubusercontent.com/75224771/102692652-09bc1680-4215-11eb-8d9e-e1bdba67c1a0.png)
this is with Friend Notifications plugin enabled, which moves server list a little down, so you can clearly see the sack icon bellow first server icon (the cat). Vanilla discord:
![image](https://user-images.githubusercontent.com/75224771/102692681-37a15b00-4215-11eb-9f3e-45be2a23acef.png)
the flat white lines can also be seen, and the whole box of where the ,,library" tile can be clicked overlaps with the first server pic, unlike the ,,friends" tile which ends with the left list:
![image](https://user-images.githubusercontent.com/75224771/102692707-61f31880-4215-11eb-8ab4-bf5357df7f26.png)
is it possible to make the tiles the same size by reducing the Library tile to make it smaller and right bellow Friends tile?

Other useful feature i can suggest is resizable server list as it can look pretty small in high resolutions.

Another (this would be a feature request) thing i wanted to ask is if it would be possible to make it work with Game Activity Toggle plugin, but its really a secondary thing. 

Have a good day and thanks for reading. Thanks for the amazing theme! And of course, marry Xmas.

**Comment by TakosThings** [comment]
Until a few weeks ago there was a User Settings option to hide the store and library tabs, and it appears to be forced on now which means this is effectively unfixable from my side.

> resizable server list

This likely wouldn't be possible due to the complicated way the guilds list is structured.

>  Game Activity Toggle plugin

I'm not currently working on maintaining BD plugins (See #192). There was work done in 3.15.0 to make it easier for plugin CSS to be added if people are interested.
