### ISSUE TITLE
Black Box on the left side of a stream

### ISSUE THREAD

**Issue by Social-Interactive** [TakosThings/Metro-for-Discord#255]
![Screenshot 2021-07-03 233028](https://user-images.githubusercontent.com/72802595/124367364-c415e700-dc56-11eb-9a8a-ecae916a1218.png)
Theres a big black block on the right of a stream

**Comment by TakosThings** [comment]
I'm not able to replicate this issue. There's currently no CSS in the theme applied to that aspect of voice/video calls, so I'm leaning towards this might be due to a large screen resolution?

**Comment by CloudX713** [comment]
Hello, thanks for answering. My Res is set to 1920 to 1080. This problem stays after redownloading.
Info:Stable 89550 (3c2108a)
BetterDiscord 1.1.1
Host 1.0.9002 Windows 10 64-Bit (10.0.19043)
Metro for Discord Version 3.15.20
Need more Info, dont hesitate to comment back.

**Comment by CloudX713** [comment]
Plugins: WhoReacted
v1.2.3by Jaime Filho

Shows the avatars of the users who reacted to a message.



VoiceUsersCounter
v2.0.0by Strencher

Adds a count of users they're connected to a VoiceChannel. Customize the Color of the count in the SettingsPanel.



UserVolumeBooster
v1.0.0by QWERT

Allows you to set a user's volume above the normal 200%



UserDetails
v1.4.3by Strencher

Shows you a lot information about users in popouts.



TypingIndicator
v0.5.2by l0c4lh057

Shows an indicator in the guild/channel list when someone is typing there



ThemeRepo
v2.2.6by DevilBro

Allows you to download all Themes from BD's Website within Discord


SteamProfileLink
v1.1.1by DevilBro

Opens Steam Links in Steam instead of your Browser



StaffTag
v1.4.6by DevilBro

Adds a Crown/Tag to Server Owners (or Admins/Management)




ShowConnections
v1.0.5by DevilBro

Shows the connected Accounts of a User in the UserPopout




ServerSearch
v0.1.5by Zerebos

Adds a button to search your servers. Search in place or in popout.


SendLargeMessages
v1.6.8by DevilBro

Allows you to enter larger Messages, which will automatically split into several smaller Messages




RoleMembers
v0.1.13by Zerebos

Allows you to see the members of each role on a server.


RedditMentions
v1.0.0by Bread

Renders subreddit and user mentions as hyperlinks


ReadAllNotificationsButton
v1.6.8by DevilBro

Adds a Clear Button to the Server List and the Mentions Popout



PluginRepo
v2.2.6by DevilBro

Allows you to download all Plugins from BD's Website within Discord


PermissionsViewer
v0.1.17by Zerebos

Allows you to view a user's permissions. Thanks to Noodlebox for the idea!



NotificationSounds
v3.6.2by DevilBro

Allows you to replace the native Sounds with custom Sounds




MultiUploads
v1.1.5by Lighty

Multiple uploads send in a single message, like on mobile. Hold shift while pressing the upload button to only upload one. Adds ability to paste multiple times.


MentionChannels
v1.0.2by CT-1409

Adds a button that puts the mention for the channel clicked in your message, like Discord does for users.


MemberCount
v2.2.4by Arashiryuu

Displays a server's member-count at the top of the member-list, can be styled with the #MemberCount selector.


LinkChannels
v1.0.3by Strencher

Adds an Icon to channels that copys <#channelId>. (channelId is replaced) Shift + Click to insert the channel in the textarea.


KeywordTracker
v1.0.7by sawahkitty!~<3

Watch for certain phrases in specified channels, and ping if one is found.



ImageUtilities
v4.4.1by DevilBro

Adds several Utilities for Images/Videos (Gallery, Download, Reverse Search, Zoom, Copy, etc.)




Hastebin
v1.0.1by CT-1409

Uploads text to https://hastebin.com


GuildProfile
v1.2.0by Marmota (Jaime Filho)

Adds a modal that can be opened via any guild menu and contains various information about the guild, such as its owner, creation date, joined date, your friends and blocked users who are in it, and much more.



GuildAndFriendRemovalAlerts
v3.0.0by Metalloriff

Displays alerts when you are kicked/banned from a server, a server is deleted, and when a friend removes you.



GoogleTranslateOption
v2.2.7by DevilBro

Allows you to translate Messages and your outgoing Message within Discord




GlobalReplies
v1.0.0by QWERT

Allows you to reply to messages outside of the channel they were sent in.



FriendNotifications
v1.7.5by DevilBro

Shows a Notification when a Friend or a User, you choose to observe, changes their Status




EmojiStatistics
v2.9.8by DevilBro

Shows you an Overview of Emojis and Emoji Servers



EditUsers
v4.3.7by DevilBro

Allows you to locally edit Users



EditServers
v2.3.3by DevilBro

Allows you to locally edit Servers




EditRoles
v1.0.5by DevilBro

Allows you to locally edit Roles




EditChannels
v4.3.2by DevilBro

Allows you to locally edit Channels




DashToSpaceInChannelName
v0.0.6by Niemiets

Changes dashes in channels name to spaces


CrashRecovery
v1.0.3by Lighty

In the event that your Discord crashes, the plugin enables you to get Discord back to a working state, without needing to reload at all.



Copier
v0.0.6by Strencher

Allows you to copy certain stuff with custom options.



ClickableMentions
v1.0.1by DevilBro

Allows you to open a User Popout by clicking a Mention in your Message Input


CharCounter
v1.5.4by DevilBro

Adds a Character Counter to most Inputs



BetterSearchPage
v1.2.0by DevilBro

Adds some extra Controls to the Search Results Page




BetterRoleColors
v0.8.14by Zerebos

Adds server-based role colors to typing, voice, popouts, modals and more!



BetterNsfwTag
v1.2.7by DevilBro

Adds a more noticeable Tag to NSFW Channels



BetterFormattingRedux
v2.3.11by Zerebos

Enables different types of formatting in standard Discord chat.



BetterFolders
v2.3.1by Zerthox

Add new functionality to server folders.



BetterBannedUsers
v1.0.1by Strencher

Enhances the banned users page.



BDContextMenu
v0.1.9by Zerebos

Adds BD shortcuts to the settings context menu.


BadgesEverywhere
v1.7.7by DevilBro

Displays Badges (Nitro, Hypesquad, etc...) in the Chat/MemberList




AutoStartRichPresence
v2.0.4by Lucario ☉ ∝ x²#7902

Auto starts Rich Presence with configurable settings. Check the website for troubleshooting/FAQs before requesting support. DM the author or create an issue for support.



AssignBadges
v1.0.1by QWERT

Allows you to locally assign badges to users through the user context menu.


AccountDetailsPlus
v0.1.10by Zerebos

Lets you view popout, nickname and more from your account panel at the bottom.



XenoLib
v1.3.39by Lighty

Simple library to complement plugins with shared code without lowering performance. Also adds needed buttons to some plugins.



ZeresPluginLibrary
v1.2.30by Zerebos

Gives other plugins utility functions and the ability to emulate v2.


BDFDB
v1.7.4by DevilBro

Required Library for DevilBro's Plugins

**Comment by CloudX713** [comment]
![Screenshot 2021-07-05 202351](https://user-images.githubusercontent.com/72802595/124507890-10843280-ddcf-11eb-912b-7504ec30b11e.png)
Full Screenshot here

**Comment by CloudX713** [comment]
> I'm not able to replicate this issue. There's currently no CSS in the theme applied to that aspect of voice/video calls, so I'm leaning towards this might be due to a large screen resolution?

How I said, its like a normal resolution, I uploaded a List with all Plugins, there may be an Issue. I dont know how to replicate.

![Screenshot 2021-07-06 203928](https://user-images.githubusercontent.com/72802595/124651011-b2bd1c80-de9a-11eb-8777-6d21384fd676.png)

**Comment by TakosThings** [comment]
You'll have to disable all plugins then enable each one individually to diagnose which plugin may be causing the issue.

**Comment by CloudX713** [comment]
> You'll have to disable all plugins then enable each one individually to diagnose which plugin may be causing the issue.

Deactivated all Plugins, Problem remain. Waiting for further Instructions.

**Comment by TakosThings** [comment]
Narrowed down the issue, implementing fix
