### ISSUE TITLE
Discussion: Changes in 3.10.2

### ISSUE THREAD

**Issue by TakosThings** [TakosThings/Metro-for-Discord#73]
This issue is to serve as a discussion about proposed changes in 3.10.2

## Significant changes
* The Guilds list will be rewritten and redesigned.
  * Primary goal is to not use the current tiles design, as it looks dated (This design is from the original v2 release)
* The usage of accent colours in the guilds and channels list will change
  * Currently the Accent colour is used to indicate a guild or channel which has unread messages. In 3.10.2 the accent colour will be used to indicate which guild or channel you currently have selected. This will improve consistency through the theme

## Other Changes
* Version info
  * The theme name and version number will be removed from its current location (below the account box). Instead it will appear within a 'toast' in the bottom right corner of the window for approx. 10 seconds, then disappear. Version info will be shown in the User Settings menu, should users require it
* Voice connection controls
  * Mic/Speaker muting, info, and disconnect buttons will be hidden when you are not connected to a voice channel
* Fluent stuff
People have previously asked me about playing with Acrylic effects. I'm still on the fence about it... (but [here](https://media.discordapp.net/attachments/329165558845276163/416968062948868107/unknown.png) is a mock up I did early last year. IMO it's a bit naff) Thoughts? Going back and doing something like this would require a lot of work, and there are also technical limitations (such as not being able to use your actual desktop background for the acrylic effect) but if it's *really* wanted now would be the time to do it

All changes are being made in the `3.10.2` branch. Dist files are not up to date in this branch, so you will have to build your own preview

**Comment by silent** [comment]
This seems pretty good but I do not wish to have the Acrylic effects that just seems useless.

**Comment by tryoutuser** [comment]
I have no problems with the significant changes and the first and second other changes, sounds it will be good to me.

But 'Acrylic' effect though, does it cause lag or heavy to discord client itself? Because for current version, the animation when I click discord settings, has a little bit of lags.

If you can, please resize this top buttons to square again like old version 2?
![image](https://user-images.githubusercontent.com/35561383/52182041-8ca77400-282b-11e9-9288-2ab8f7c368d8.png)
Cause on me it looks rectangle than square. Just a suggestion for upcoming update.
