### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by silent** [TakosThings/Metro-for-Discord#77]
I use the experimental Guild Video and now it doesn't show the icon properly in the new theme update
![image](https://user-images.githubusercontent.com/36117192/53282375-5d827500-36fc-11e9-887c-3fed168a01ed.png)
vs
![image](https://user-images.githubusercontent.com/36117192/53282452-835c4980-36fd-11e9-9b94-cc0c0b230c05.png)

Unread channels are now white instead of blue:
![image](https://user-images.githubusercontent.com/36117192/53282384-6b37fa80-36fc-11e9-8cac-35edea0f99c1.png)
Really annoying as I am used to it being blue.

Viewing a channel is now blue vs white
![image](https://user-images.githubusercontent.com/36117192/53282400-8e62aa00-36fc-11e9-88fa-958cfed717a6.png)

Guild List doesn't have a true distinction between new messages in a server and a selected server as seen here but also the colors have switched from being blue vs white 
![image](https://user-images.githubusercontent.com/36117192/53282578-42fdcb00-36ff-11e9-8720-0e33c0987b66.png)

Old version showed: 
![image](https://user-images.githubusercontent.com/36117192/53282568-0631d400-36ff-11e9-9860-b576179d3b9d.png)

Overall this new update looks good though just those minor things are a bit annoying but everything else looks great :+1:

**Comment by tryoutuser** [comment]
Uhh imo the selected and unread color for text channels or servers is now based on actual windows 10 settings. When you selected a submenu, it will show a little blue bars at the left side of menu title just like current version.

**Comment by silent** [comment]
While that may be true, but as someone who has been using Metro For Discord for a while now, I am used to how it was and at least an option to go back to how it was would be very useful.

**Comment by tryoutuser** [comment]
Oh yeah Tako will you restore GIF button located besides emoji?

**Comment by silent** [comment]
That should be an option as currently, that's useless IMO. If you want to use gifs just type /tenor or /giphy pretty easy.

**Comment by TakosThings** [comment]
Probably should update this thread...

**Guild video**
I currently don't have access to the guild video feature, so not too much I can do on that for now.

**Accent Colour Change**  
@tryoutuser is correct, as also mentioned in [CHANGELOG.md](https://github.com/TakosThings/Metro-for-Discord/blob/f1ad1be59cf4d24de051d09ab8ed208c700d997e/CHANGELOG.md) and #73. The Channels list CSS is immensely convoluted which is why it remained 'incorrect' for such a long time.

**GIF Button**  
It is very unlikely that the button will come back. As with @silent, I agree that's it doesn't really serve a purpose.<sup>1</sup>

<sup>1</sup> - (I had touched upon this in CHANGELOG.md at the time with more detail to be in CONTRIBUTING.md, but that's still a WIP.)

**Comment by silent** [comment]
You can access the guild video feature using: https://github.com/Inve1951/BetterDiscordStuff/blob/master/plugins/discordexperiments.plugin.js

I'd really wish I could have the old accent colours as I am still using 3.10.1 as I am used to the previous colours lol.

**Comment by tryoutuser** [comment]
Okay, will you consider or tell users how to restore the button despite it won't be designed?

**Comment by silent** [comment]
After using the new version I have got used to how it is. Thanks though for keeping it open.
